### ISSUE TITLE
The email you sent me to verify my account did not work.

### ISSUE THREAD

**Issue by Sleepingwell** [Mermaid-Chart/issue-tracker#64]
**Describe the bug**
See the title.

**To Reproduce**
Try to create an account and click the link in the confirmation email.

**Expected behavior**
My account is confirmed.

**Comment by huynhicode** [comment]
Hi @Sleepingwell, sorry to hear you are having difficulty verifying your account.

Would you please send us an email at hello@mermaidchart.com so that we can best assist you? 

Please provide:
- the email address you used to create your account
- any error messages (screenshots are really helpful too!)

**Comment by jgreywolf** [comment]
@Sleepingwell Has this issue been resolved?

What behavior did you encounter?

**Comment by Sleepingwell** [comment]
It has been resolved. Not sure what changed but eventually the link in the email worked.
