### ISSUE TITLE
Rendering source code in prod

### ISSUE THREAD

**Issue by iamnathanwindsor** [Mermaid-Chart/issue-tracker#9]
**Describe the bug**
I've had the Mermaid plugin installed for months, but now it also renders the source code. How do I fix this?

I uninstalled and reinstalled the plugin, but no success.

**To Reproduce**
1. Go to https://docs.landslide.network/product-guides/landslide-and-tendermint
You'll see the source code rendered.

**Expected behavior**
You should only see Mermaid code on the live site.

**Screenshots**
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/14031909/b1dc7769-852a-4e11-bf0b-ae05a2ecde46)

**Desktop
 - OS: Mac
 - Browser Chrome
 - Version 115.0.5790.170
 
**Smartphone
 - Device: iPhone 14 Max Pro
 - OS: 16.5.1
 - Browser Brave
 - Version 1.52.1

**Comment by knsv** [comment]
This looks like a notion specific issue. I would suggest to register this issue with them. We are planning to create a dedicated Mermaid Chart plugin for notion but that work has not started yet.

**Comment by iamnathanwindsor** [comment]
Sorry I don't understand what you mean.

This is a Gitbook issue, not a Notion issue.

Gitbook has indeed acknowledged it too, but they say there is no fix to it.

Any chance the Mermaid team can help?

Otherwise I'll just export PNGs

**Comment by knsv** [comment]
Thank you for reaching out. While the issue seems to be originating from Gitbook's plugin handling, we appreciate your interest in finding a solution with Mermaid.

We can't directly influence how third-party plugins interpret our code, but we're always open to exploring potential workarounds. For now, exporting to PNG remains a practical alternative.

Best regards,
Knut

**Comment by iamnathanwindsor** [comment]
Ok thanks.

I hope you guys work with them to fix it.
